[package]
name = "diagnostic-example"
version = "0.0.0"
authors = ["Sergio Benitez <sb@sergio.bz>"]
edition = "2018"
publish = false

[lib]
proc-macro = true

[dependencies]
proc-macro2-diagnostics = { path = ".." }
quote = "1.0"
proc-macro2 = "1.0"
syn = "2.0"
