[package]
name = "proc-macro2-diagnostics"
version = "0.10.1"
authors = ["Sergio Benitez <sb@sergio.bz>"]
description = "Diagnostics for proc-macro2."
license = "MIT/Apache-2.0"
edition = "2018"
readme = "README.md"
repository = "https://github.com/SergioBenitez/proc-macro2-diagnostics"
homepage = "https://github.com/SergioBenitez/proc-macro2-diagnostics"
documentation = "https://docs.rs/proc-macro2-diagnostics"

[features]
default = ["colors"]
colors = ["yansi"]
nightly = ["dep:version_check"]

[dependencies]
quote = "1.0"
proc-macro2 = "1.0"
yansi = { version = "1.0.1", optional = true }

[dependencies.syn]
version = "2"
default-features = false
features = ["parsing", "printing"]

[build-dependencies]
version_check = { version = "0.9.4", optional = true }

[dev-dependencies]
trybuild = "1.0"
diagnostic-example = { path = "example/" }

[workspace]
# Needed to keep features for dependencies & dev-dependencies seperate
resolver = "2"
